apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: galasa-tekton
  annotations:
    tekton.dev/git-0: https://api.github.com/repos/galasa-dev/framework
    tekton.dev/git-1: https://api.github.com/repos/galasa-dev/extentions
    tekton.dev/git-2: https://api.github.com/repos/galasa-dev/managers
    tekton.dev/git-3: https://api.github.com/repos/galasa-dev/galasa-docker-operator
    tekton.dev/git-4: https://api.github.com/repos/galasa-dev/galasa-kubernetes-operator
    tekton.dev/git-5: https://api.github.com/repos/galasa-dev/buildutils
type: kubernetes.io/basic-auth
stringData:
  username: cicsdeliverytest
  token: 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
