apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-polling-controller
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-polling-controller
      app.kubernetes.io/component: polling
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-polling
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tekton-polling-controller
        app.kubernetes.io/component: polling
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "v1alpha1"
        app.kubernetes.io/part-of: tekton-polling
        app: tekton-poll-controller
        version: "v1alpha1"
    spec:
      serviceAccountName: tekton-polling-controller
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: tekton-polling-controller
        image: ko://github.com/tektoncd/experimental/polling/cmd/controller
        # image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/library/tekton-polling-controller:v1alpha1
        # args:
        #   - "-namespace"
        #   - "tekton"
        env:
        - name: METRICS_DOMAIN
          value: tekton.dev/polling
        - name: KUBERNETES_MIN_VERSION
          value: 1.17.13
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          # User 65532 is the distroless nonroot user ID
          runAsUser: 65532
          runAsGroup: 65532