/*
Copyright 2021 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/polling/pkg/apis/scmpoll/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSCMPolls implements SCMPollInterface
type FakeSCMPolls struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var scmpollsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "scmpolls"}

var scmpollsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "SCMPoll"}

// Get takes name of the sCMPoll, and returns the corresponding sCMPoll object, and an error if there is any.
func (c *FakeSCMPolls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SCMPoll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scmpollsResource, c.ns, name), &v1alpha1.SCMPoll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPoll), err
}

// List takes label and field selectors, and returns the list of SCMPolls that match those selectors.
func (c *FakeSCMPolls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SCMPollList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scmpollsResource, scmpollsKind, c.ns, opts), &v1alpha1.SCMPollList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SCMPollList{ListMeta: obj.(*v1alpha1.SCMPollList).ListMeta}
	for _, item := range obj.(*v1alpha1.SCMPollList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sCMPolls.
func (c *FakeSCMPolls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scmpollsResource, c.ns, opts))

}

// Create takes the representation of a sCMPoll and creates it.  Returns the server's representation of the sCMPoll, and an error, if there is any.
func (c *FakeSCMPolls) Create(ctx context.Context, sCMPoll *v1alpha1.SCMPoll, opts v1.CreateOptions) (result *v1alpha1.SCMPoll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scmpollsResource, c.ns, sCMPoll), &v1alpha1.SCMPoll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPoll), err
}

// Update takes the representation of a sCMPoll and updates it. Returns the server's representation of the sCMPoll, and an error, if there is any.
func (c *FakeSCMPolls) Update(ctx context.Context, sCMPoll *v1alpha1.SCMPoll, opts v1.UpdateOptions) (result *v1alpha1.SCMPoll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scmpollsResource, c.ns, sCMPoll), &v1alpha1.SCMPoll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPoll), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSCMPolls) UpdateStatus(ctx context.Context, sCMPoll *v1alpha1.SCMPoll, opts v1.UpdateOptions) (*v1alpha1.SCMPoll, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scmpollsResource, "status", c.ns, sCMPoll), &v1alpha1.SCMPoll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPoll), err
}

// Delete takes name of the sCMPoll and deletes it. Returns an error if one occurs.
func (c *FakeSCMPolls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scmpollsResource, c.ns, name), &v1alpha1.SCMPoll{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSCMPolls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scmpollsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SCMPollList{})
	return err
}

// Patch applies the patch and returns the patched sCMPoll.
func (c *FakeSCMPolls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SCMPoll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scmpollsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SCMPoll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPoll), err
}
