/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/polling/pkg/apis/scmpoll/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSCMPollStates implements SCMPollStateInterface
type FakeSCMPollStates struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var scmpollstatesResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "scmpollstates"}

var scmpollstatesKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "SCMPollState"}

// Get takes name of the sCMPollState, and returns the corresponding sCMPollState object, and an error if there is any.
func (c *FakeSCMPollStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SCMPollState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scmpollstatesResource, c.ns, name), &v1alpha1.SCMPollState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPollState), err
}

// List takes label and field selectors, and returns the list of SCMPollStates that match those selectors.
func (c *FakeSCMPollStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SCMPollStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scmpollstatesResource, scmpollstatesKind, c.ns, opts), &v1alpha1.SCMPollStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SCMPollStateList{ListMeta: obj.(*v1alpha1.SCMPollStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.SCMPollStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sCMPollStates.
func (c *FakeSCMPollStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scmpollstatesResource, c.ns, opts))

}

// Create takes the representation of a sCMPollState and creates it.  Returns the server's representation of the sCMPollState, and an error, if there is any.
func (c *FakeSCMPollStates) Create(ctx context.Context, sCMPollState *v1alpha1.SCMPollState, opts v1.CreateOptions) (result *v1alpha1.SCMPollState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scmpollstatesResource, c.ns, sCMPollState), &v1alpha1.SCMPollState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPollState), err
}

// Update takes the representation of a sCMPollState and updates it. Returns the server's representation of the sCMPollState, and an error, if there is any.
func (c *FakeSCMPollStates) Update(ctx context.Context, sCMPollState *v1alpha1.SCMPollState, opts v1.UpdateOptions) (result *v1alpha1.SCMPollState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scmpollstatesResource, c.ns, sCMPollState), &v1alpha1.SCMPollState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPollState), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSCMPollStates) UpdateStatus(ctx context.Context, sCMPollState *v1alpha1.SCMPollState, opts v1.UpdateOptions) (*v1alpha1.SCMPollState, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scmpollstatesResource, "status", c.ns, sCMPollState), &v1alpha1.SCMPollState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPollState), err
}

// Delete takes name of the sCMPollState and deletes it. Returns an error if one occurs.
func (c *FakeSCMPollStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scmpollstatesResource, c.ns, name), &v1alpha1.SCMPollState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSCMPollStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scmpollstatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SCMPollStateList{})
	return err
}

// Patch applies the patch and returns the patched sCMPollState.
func (c *FakeSCMPollStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SCMPollState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scmpollstatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SCMPollState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SCMPollState), err
}
