/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/polling/pkg/apis/poll/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolls implements PollInterface
type FakePolls struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var pollsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "polls"}

var pollsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "Poll"}

// Get takes name of the poll, and returns the corresponding poll object, and an error if there is any.
func (c *FakePolls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Poll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pollsResource, c.ns, name), &v1alpha1.Poll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poll), err
}

// List takes label and field selectors, and returns the list of Polls that match those selectors.
func (c *FakePolls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PollList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pollsResource, pollsKind, c.ns, opts), &v1alpha1.PollList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PollList{ListMeta: obj.(*v1alpha1.PollList).ListMeta}
	for _, item := range obj.(*v1alpha1.PollList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested polls.
func (c *FakePolls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pollsResource, c.ns, opts))

}

// Create takes the representation of a poll and creates it.  Returns the server's representation of the poll, and an error, if there is any.
func (c *FakePolls) Create(ctx context.Context, poll *v1alpha1.Poll, opts v1.CreateOptions) (result *v1alpha1.Poll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pollsResource, c.ns, poll), &v1alpha1.Poll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poll), err
}

// Update takes the representation of a poll and updates it. Returns the server's representation of the poll, and an error, if there is any.
func (c *FakePolls) Update(ctx context.Context, poll *v1alpha1.Poll, opts v1.UpdateOptions) (result *v1alpha1.Poll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pollsResource, c.ns, poll), &v1alpha1.Poll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poll), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolls) UpdateStatus(ctx context.Context, poll *v1alpha1.Poll, opts v1.UpdateOptions) (*v1alpha1.Poll, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pollsResource, "status", c.ns, poll), &v1alpha1.Poll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poll), err
}

// Delete takes name of the poll and deletes it. Returns an error if one occurs.
func (c *FakePolls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pollsResource, c.ns, name), &v1alpha1.Poll{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pollsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PollList{})
	return err
}

// Patch applies the patch and returns the patched poll.
func (c *FakePolls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Poll, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pollsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Poll{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poll), err
}
