/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/polling/pkg/apis/poll/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePollRuns implements PollRunInterface
type FakePollRuns struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var pollrunsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "pollruns"}

var pollrunsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "PollRun"}

// Get takes name of the pollRun, and returns the corresponding pollRun object, and an error if there is any.
func (c *FakePollRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PollRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pollrunsResource, c.ns, name), &v1alpha1.PollRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PollRun), err
}

// List takes label and field selectors, and returns the list of PollRuns that match those selectors.
func (c *FakePollRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PollRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pollrunsResource, pollrunsKind, c.ns, opts), &v1alpha1.PollRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PollRunList{ListMeta: obj.(*v1alpha1.PollRunList).ListMeta}
	for _, item := range obj.(*v1alpha1.PollRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pollRuns.
func (c *FakePollRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pollrunsResource, c.ns, opts))

}

// Create takes the representation of a pollRun and creates it.  Returns the server's representation of the pollRun, and an error, if there is any.
func (c *FakePollRuns) Create(ctx context.Context, pollRun *v1alpha1.PollRun, opts v1.CreateOptions) (result *v1alpha1.PollRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pollrunsResource, c.ns, pollRun), &v1alpha1.PollRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PollRun), err
}

// Update takes the representation of a pollRun and updates it. Returns the server's representation of the pollRun, and an error, if there is any.
func (c *FakePollRuns) Update(ctx context.Context, pollRun *v1alpha1.PollRun, opts v1.UpdateOptions) (result *v1alpha1.PollRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pollrunsResource, c.ns, pollRun), &v1alpha1.PollRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PollRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePollRuns) UpdateStatus(ctx context.Context, pollRun *v1alpha1.PollRun, opts v1.UpdateOptions) (*v1alpha1.PollRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pollrunsResource, "status", c.ns, pollRun), &v1alpha1.PollRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PollRun), err
}

// Delete takes name of the pollRun and deletes it. Returns an error if one occurs.
func (c *FakePollRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pollrunsResource, c.ns, name), &v1alpha1.PollRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePollRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pollrunsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PollRunList{})
	return err
}

// Patch applies the patch and returns the patched pollRun.
func (c *FakePollRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PollRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pollrunsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PollRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PollRun), err
}
