// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	if in.SCMPollParams != nil {
		in, out := &in.SCMPollParams, &out.SCMPollParams
		*out = make([]v1beta1.Param, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPoll) DeepCopyInto(out *SCMPoll) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPoll.
func (in *SCMPoll) DeepCopy() *SCMPoll {
	if in == nil {
		return nil
	}
	out := new(SCMPoll)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SCMPoll) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollList) DeepCopyInto(out *SCMPollList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SCMPoll, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollList.
func (in *SCMPollList) DeepCopy() *SCMPollList {
	if in == nil {
		return nil
	}
	out := new(SCMPollList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SCMPollList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollSpec) DeepCopyInto(out *SCMPollSpec) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PipelineRunSpec.DeepCopyInto(&out.PipelineRunSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollSpec.
func (in *SCMPollSpec) DeepCopy() *SCMPollSpec {
	if in == nil {
		return nil
	}
	out := new(SCMPollSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollState) DeepCopyInto(out *SCMPollState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollState.
func (in *SCMPollState) DeepCopy() *SCMPollState {
	if in == nil {
		return nil
	}
	out := new(SCMPollState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SCMPollState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollStateList) DeepCopyInto(out *SCMPollStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SCMPollState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollStateList.
func (in *SCMPollStateList) DeepCopy() *SCMPollStateList {
	if in == nil {
		return nil
	}
	out := new(SCMPollStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SCMPollStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollStateSpec) DeepCopyInto(out *SCMPollStateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollStateSpec.
func (in *SCMPollStateSpec) DeepCopy() *SCMPollStateSpec {
	if in == nil {
		return nil
	}
	out := new(SCMPollStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollStateStatus) DeepCopyInto(out *SCMPollStateStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.SCMPollStateStatusFields.DeepCopyInto(&out.SCMPollStateStatusFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollStateStatus.
func (in *SCMPollStateStatus) DeepCopy() *SCMPollStateStatus {
	if in == nil {
		return nil
	}
	out := new(SCMPollStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollStateStatusFields) DeepCopyInto(out *SCMPollStateStatusFields) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.NextPoll != nil {
		in, out := &in.NextPoll, &out.NextPoll
		*out = (*in).DeepCopy()
	}
	if in.SCMPollStates != nil {
		in, out := &in.SCMPollStates, &out.SCMPollStates
		*out = make(map[string]*SCMRepositoryStatus, len(*in))
		for key, val := range *in {
			var outVal *SCMRepositoryStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SCMRepositoryStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollStateStatusFields.
func (in *SCMPollStateStatusFields) DeepCopy() *SCMPollStateStatusFields {
	if in == nil {
		return nil
	}
	out := new(SCMPollStateStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMPollStatus) DeepCopyInto(out *SCMPollStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMPollStatus.
func (in *SCMPollStatus) DeepCopy() *SCMPollStatus {
	if in == nil {
		return nil
	}
	out := new(SCMPollStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMRepositoryStatus) DeepCopyInto(out *SCMRepositoryStatus) {
	*out = *in
	if in.StatusParams != nil {
		in, out := &in.StatusParams, &out.StatusParams
		*out = make([]v1beta1.Param, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMRepositoryStatus.
func (in *SCMRepositoryStatus) DeepCopy() *SCMRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(SCMRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}
